In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/retail_store_sales_dataset.csv")

In [ ]:
df.head()

,transaction_id,city,store,product_category,product_name,unit_price,quantity,customer_type,payment_method,discount_percent,total_sale,discount_amount,final_amount
0,5001,Pune,Central Mall,Home Decor,Face Cream,2386,4,Returning,Card,15,9544,1431.60,8112.40
1,5002,Bangalore,City Center,Home Decor,Wall Lamp,1383,1,New,Card,10,1383,138.30,1244.70
2,5003,Hyderabad,Central Mall,Clothing,Jeans,4937,1,Returning,UPI,5,4937,246.85,4690.15
3,5004,Hyderabad,Smart Bazaar,Home Decor,Mixer,1470,2,Returning,UPI,10,2940,294.00,2646.00
4,5005,Hyderabad,Central Mall,Beauty,Headphones,2688,1,New,Cash,10,2688,268.80,2419.20

In [ ]:
df.shape   #How many transactions are recorded in the dataset?

(220, 13)

In [ ]:
df["city"]    #What are the different cities present in the dataset?

0           Pune
1      Bangalore
2      Hyderabad
3      Hyderabad
4      Hyderabad
         ...
215    Hyderabad
216       Mysore
217         Pune
218      Chennai
219      Chennai
Name: city, Length: 220, dtype: object

In [ ]:
df["product_category"]   #How many product categories exist?

0       Home Decor
1       Home Decor
2         Clothing
3       Home Decor
4           Beauty
          ...
215     Home Decor
216         Beauty
217    Electronics
218      Groceries
219     Home Decor
Name: product_category, Length: 220, dtype: object

In [ ]:
df.head(10)    #Display the first 10 rows.

,transaction_id,city,store,product_category,product_name,unit_price,quantity,customer_type,payment_method,discount_percent,total_sale,discount_amount,final_amount
0,5001,Pune,Central Mall,Home Decor,Face Cream,2386,4,Returning,Card,15,9544,1431.60,8112.40
1,5002,Bangalore,City Center,Home Decor,Wall Lamp,1383,1,New,Card,10,1383,138.30,1244.70
2,5003,Hyderabad,Central Mall,Clothing,Jeans,4937,1,Returning,UPI,5,4937,246.85,4690.15
3,5004,Hyderabad,Smart Bazaar,Home Decor,Mixer,1470,2,Returning,UPI,10,2940,294.00,2646.00
4,5005,Hyderabad,Central Mall,Beauty,Headphones,2688,1,New,Cash,10,2688,268.80,2419.20
5,5006,Mysore,Urban Retail,Electronics,Rice Bag,1652,4,Returning,UPI,0,6608,0.00,6608.00
6,5007,Hyderabad,Metro Mart,Home Decor,Wall Lamp,2739,2,New,Card,15,5478,821.70,4656.30
7,5008,Chennai,Central Mall,Electronics,Mixer,3899,3,New,Cash,15,11697,1754.55,9942.45
8,5009,Pune,Central Mall,Electronics,Wall Lamp,4628,3,Returning,UPI,10,13884,1388.40,12495.60
9,5010,Bangalore,City Center,Home Decor,Wall Lamp,2414,4,Returning,Card,5,9656,482.80,9173.20

In [ ]:
df.info()   #Show the data types of each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    220 non-null    int64
 1   city              220 non-null    object
 2   store             220 non-null    object
 3   product_category  220 non-null    object
 4   product_name      220 non-null    object
 5   unit_price        220 non-null    int64
 6   quantity          220 non-null    int64
 7   customer_type     220 non-null    object
 8   payment_method    220 non-null    object
 9   discount_percent  220 non-null    int64
 10  total_sale        220 non-null    int64
 11  discount_amount   220 non-null    float64
 12  final_amount      220 non-null    float64
dtypes: float64(2), int64(5), object(6)
memory usage: 22.5+ KB

In [ ]:
df["product_category"].value_counts().idxmax()   #Which product category is sold the most?

'Groceries'

In [ ]:
df.groupby("product_category")["quantity"].sum().idxmax()

'Groceries'

In [ ]:
df.groupby("store")["total_sale"].sum().idxmax()    #Which store has the highest number of transactions?

'Smart Bazaar'

In [ ]:
df["city"].value_counts().idxmax()    #Which city has the most customers?

'Hyderabad'

In [ ]:
df["final_amount"].mean()    #What is the average purchase value (final_amount)?

np.float64(5581.942045454545)

In [ ]:
df["final_amount"].max()     #What is the maximum purchase value?

19900.0

In [ ]:
df.groupby("city")["final_amount"].sum().idxmax()     #Which city generates the highest revenue?

'Hyderabad'

In [ ]:
df["payment_method"].value_counts().idxmax()

'Card'

In [ ]:
df.groupby("customer_type")["final_amount"].sum().idxmax()

'New'

In [ ]:
df.groupby("product_category")["final_amount"].sum().idxmax()

'Groceries'

In [ ]:
df.groupby("store")["discount_amount"].sum().idxmax()

'Smart Bazaar'

In [ ]:
df.groupby("product_name")["quantity"].sum().idxmax()

'Mixer'

In [ ]:
df.groupby("city")["final_amount"].mean().idxmax()

'Mysore'

In [ ]:
cu_returning=df[df["customer_type"]=="Returning"]
cu_returning

,transaction_id,city,store,product_category,product_name,unit_price,quantity,customer_type,payment_method,discount_percent,total_sale,discount_amount,final_amount
0,5001,Pune,Central Mall,Home Decor,Face Cream,2386,4,Returning,Card,15,9544,1431.60,8112.40
2,5003,Hyderabad,Central Mall,Clothing,Jeans,4937,1,Returning,UPI,5,4937,246.85,4690.15
3,5004,Hyderabad,Smart Bazaar,Home Decor,Mixer,1470,2,Returning,UPI,10,2940,294.00,2646.00
5,5006,Mysore,Urban Retail,Electronics,Rice Bag,1652,4,Returning,UPI,0,6608,0.00,6608.00
8,5009,Pune,Central Mall,Electronics,Wall Lamp,4628,3,Returning,UPI,10,13884,1388.40,12495.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,5212,Pune,Central Mall,Groceries,Wall Lamp,1447,3,Returning,Card,20,4341,868.20,3472.80
212,5213,Hyderabad,Smart Bazaar,Clothing,Wall Lamp,4717,3,Returning,Cash,5,14151,707.55,13443.45
213,5214,Mysore,Urban Retail,Electronics,Mixer,2483,3,Returning,Card,10,7449,744.90,6704.10
216,5217,Mysore,Urban Retail,Beauty,Rice Bag,4696,1,Returning,Cash,15,4696,704.40,3991.60
219,5220,Chennai,Central Mall,Home Decor,Headphones,2783,1,Returning,Card,10,2783,278.30,2504.70

In [ ]:
cu_returning.groupby("product_category")["customer_type"].sum().idxmax()

'Groceries'

In [ ]:
cu_returning["product_category"].value_counts().idxmax()

'Groceries'